- packages/frontend/src/components/swap/Swap.js
Hide USN from swaps until it is fixed
> fix: hide usn from swaps

- packages/frontend/src/hooks/useTokenBlacklist.js
- packages/frontend/src/routes/WalletWrapper.js
Most basic implementation of black-list
TODO: add dynamic fetching of the list
> MYNW-215: add simple FT block-list implementation

- packages/frontend/declarations.d.ts
- packages/frontend/package.json
- packages/frontend/src/components/profile/balances/BalanceContainer.js
- packages/frontend/src/mixpanel/index.js
- packages/frontend/tsconfig.json
At the current time there are 1139 ts erros
> feat: add ts basic support

- features/features.d.ts
- features/flags.json
- packages/frontend/src/components/send/components/RiscScoringForm.js
https://mnw.atlassian.net/browse/MNW-91
> feat: enable HAPI checks on mainnet

- packages/frontend/src/components/common/token/TokenBox.js
- packages/frontend/src/services/FungibleTokens.js
NEAR sending:
https://www.loom.com/share/5786ec86b7b940b9a3d62786d2c2e0ed
Tokens display:
> MNW fix NEAR sending

- packages/frontend/src/components/common/balance/helpers.js
- packages/frontend/src/components/send/SendContainerWrapper.js
https://mnw.atlassian.net/browse/MNW-67
> fix: tuned display error msg in near instead yoctonear

- packages/frontend/src/config/environmentDefaults/development.js
- packages/frontend/src/config/environmentDefaults/mainnet.js
- packages/frontend/src/config/environmentDefaults/mainnet_STAGING.js
- packages/frontend/src/config/environmentDefaults/testnet.js
- packages/frontend/src/config/environmentDefaults/testnet_STAGING.js
Task: https://mnw.atlassian.net/browse/MNW-242
> MNW-242 Replace blacklist endpoints

- packages/frontend/src/components/wallet/CreateCustomNameLightBanner.js
- packages/frontend/src/components/wallet/ExploreNativeBanner.js
- packages/frontend/src/components/wallet/Wallet.js
Tasks:
- https://mnw.atlassian.net/browse/MNW-272
- https://mnw.atlassian.net/browse/MNW-273
Events:
- **Top up**
- **Explore Apps**
- **Add a Custom Address**
> MNW Add new events

- packages/frontend/src/config/environmentDefaults/development.ts
- packages/frontend/src/config/environmentDefaults/mainnet.ts
- packages/frontend/src/config/environmentDefaults/mainnet_STAGING.ts
- packages/frontend/src/config/environmentDefaults/testnet.ts
- packages/frontend/src/config/environmentDefaults/testnet_STAGING.ts
- packages/frontend/src/favicon.svg
- packages/frontend/src/pages/TokenSwap/utils/constants.js
- replace favicon svg code
- set USDT as a default swap output token
> fix: correct favicon display (#74)

- packages/frontend/src/components/buy/FundingType.jsx
- packages/frontend/src/config/buyNearConfig.js
- packages/frontend/src/config/environmentDefaults/mainnet_STAGING.ts
https://mnw.atlassian.net/browse/MNW-323
Changed `'noopener'` -> `'noreferrer'` for UTORG link to make if work.
> MNW-323: Fix UTORG

- packages/frontend/package.json
- packages/frontend/src/components/accounts/batch_import_accounts/index.js
- packages/frontend/src/utils/encoding.js
- yarn.lock
> Update account import decryption

- packages/frontend/src/utils/wallet.js
> fix: linkdrop connection no call to getAccessKeys

- packages/frontend/src/utils/wallet.js
> fix: linkdrop connection no call to getAccessKeys (#100)

- .github/workflows/cloudflare-pages-deploy.yml
- .github/workflows/deploy-mnw-mainnet.yml
- .github/workflows/deploy-mnw-testnet.yml
- .github/workflows/deploy-staging.yml
- .github/workflows/pull-request.yml
Edits Github Actions to deploy the builds of the app to Cloudflare Pages, the final step in moving completely off of AWS.
> ci: change deployments from AWS to Cloudflare Pages

- packages/frontend/src/components/navigation/MobileContainer.js
> fix: support button styling

- .husky/commit-msg
- commitlint.config.js
- lerna.json
- package.json
- packages/e2e-tests/package.json
- packages/frontend/package.json
- yarn.lock
* Add commitlint
* Update husky pre-commit
* Update husky and lerna packages
> chore: add commitlint

- .husky/pre-commit
- .lintstagedrc
- .tool-versions
- package.json
- yarn.lock
Add lint staged to git commit flow and add .tool-versions file so it's clear what version of node should be used
* Added and implemented lint staged
* Added .tool-versions file
> chore: add lint staged and .tool-versions file

- packages/frontend/src/services/FungibleTokens.js
Fix fail to send certain FTs that requires deposit that's more than the minimum.
> fix: fail to send certain FTs

- packages/frontend/.storybook/preview.js
- packages/frontend/package.json
- packages/frontend/src/app/App.js
- packages/frontend/src/app/TempEvent.tsx
- packages/frontend/src/index.tsx
- packages/frontend/src/redux/actions/account.js
- packages/frontend/src/utils/query/src/index.ts
- yarn.lock
Display a modal asking user to register as a voter if they haven't
Screenshot 1: When user are logged in with multiple accounts, even when their active account don't have the SBT token, as long as any of their logged in account have SBT token, then it will not display the modal.
Screenshot 2: When user are logged in, but all of their accounts don't have SBT token, then it will display the modal
Screenshot 3: When the user are not logged in, the modal will not be displayed.
> Soulbound token

- packages/frontend/src/index.css
> fix: tailwind styles causing svg to be block instead of inline

- packages/frontend/src/utils/wallet.ts
Not done yet, don't approve and merge
> fix: use original wallet signer when using custom shard

- packages/frontend/src/config/configFromEnvironment.ts
- packages/frontend/src/config/environmentDefaults/development.ts
- packages/frontend/src/config/environmentDefaults/mainnet.ts
- packages/frontend/src/config/environmentDefaults/mainnet_STAGING.ts
- packages/frontend/src/config/environmentDefaults/testnet.ts
- packages/frontend/src/config/environmentDefaults/testnet_STAGING.ts
- packages/frontend/src/services/PrivateShard.js
Reverts mynearwallet/my-near-wallet#139
> Revert "[calimero] change sync endpoint and call payload"

- packages/frontend/src/utils/wallet.ts
Only by removing that line, PR #157 can work normally
> fix: remove the const wallet = this

- packages/e2e-tests/signMessageWithDapp/signMessage.spec.js
- packages/e2e-tests/utils/account.js
- packages/frontend/package.json
- packages/frontend/src/app/App.js
- packages/frontend/src/components/sign-message/SignMessage.js
- packages/frontend/src/components/sign-message/SignMessageInvalid.js
- packages/frontend/src/components/sign-message/SignMessageSummary.js
- packages/frontend/src/components/sign-message/SignMessageSummaryWrapper.js
- packages/frontend/src/redux/actions/account.js
- packages/frontend/src/redux/createReducers/combinedMainReducers.js
- packages/frontend/src/redux/reducers/signMessage/index.js
- packages/frontend/src/redux/slices/account/index.js
- packages/frontend/src/redux/slices/signMessage/index.js
- packages/frontend/src/routes/SignMessageWrapper.js
- packages/frontend/src/translations/locales/en/translation.json
- packages/frontend/src/utils/signMessage.ts
- packages/frontend/src/utils/wallet.ts
- packages/guestbook/src/components/Content.tsx
- yarn.lock
> feat: sign message init

- packages/frontend/src/utils/wallet.ts
Fix 2 problem
When importing multiple ledger account, got error
When retrying to import a previously imported ledger account, got error
> Fix ledger problem

- packages/frontend/src/redux/slices/security/temp_blacklisted_tokens.json
> fix: block compliment.laboratory.jumpfinance.near

- packages/frontend/src/redux/slices/tokens/index.js
- packages/frontend/src/utils/fiatValueManager.js
- packages/frontend/src/utils/token.ts
> fix: show native USDC and USDT properly

- packages/frontend/src/components/profile/full_access_key_rotations/FullAccessKeyRotation.js
Profile Account page is now broken due to a line that checks the transactionHash.length without assuring the transactionHash is not null/undefined 
Added the check before that line
> fix: hotfix on issue for key rotation

- package.json
- packages/frontend/package.json
- packages/frontend/src/app/App.js
- packages/frontend/src/services/indexer/api.ts
- yarn.lock
Account import doesn't work now since kitwallet is down and nearblocks isn't accurate.
Added mintbase data as one of the data source as well.
> fix: account import not working due to indexers

- packages/frontend/src/config/environmentDefaults/development.ts
- packages/frontend/src/config/environmentDefaults/mainnet.ts
- packages/frontend/src/config/environmentDefaults/mainnet_STAGING.ts
- packages/frontend/src/config/environmentDefaults/testnet.ts
- packages/frontend/src/config/environmentDefaults/testnet_STAGING.ts
- packages/frontend/src/services/indexer/api.ts
Nearblocks launched a new API at
https://api3.nearblocks.io/api-docs/
It is currently experimental
> feat: use nearblocks experimental api for fetching accounts

- packages/frontend/src/components/connection/AddConnectionForm.tsx
- packages/frontend/src/translations/locales/en/translation.json
- packages/frontend/src/utils/mnw-api-js/src/RpcRotator.ts
Add lava to rpc provider as another option
> add rpc provider lava

- packages/frontend/src/config/environmentDefaults/mainnet.ts
- packages/frontend/src/config/environmentDefaults/mainnet_STAGING.ts
- packages/frontend/src/services/coreIndexer/CoreIndexerAdapter.ts
- packages/frontend/src/services/coreIndexer/indexers/NearblocksV3Indexer.ts
nearblocks updated to v3 just now, because v1 having storage issue
> feat(indexer): update nearblocks endpoint

- packages/frontend/src/redux/actions/staking.js
- packages/frontend/src/services/coreIndexer/CoreIndexerAdapter.ts
- packages/frontend/src/services/coreIndexer/indexers/AbstractCoreIndexer.ts
- packages/frontend/src/services/coreIndexer/indexers/FastNearIndexer.ts
- packages/frontend/src/services/coreIndexer/indexers/MintbaseIndexer.ts
- packages/frontend/src/services/coreIndexer/indexers/NearblocksV1Indexer.ts
- packages/frontend/src/services/coreIndexer/indexers/NearblocksV3Indexer.ts
- packages/frontend/src/services/indexer.js
- packages/frontend/src/services/indexer/api.ts
- packages/frontend/src/utils/account-with-lockup.ts
- packages/frontend/src/utils/staking.ts
Some validators not showing, because not exist on near rpc response
example: aurora.poolv1.near
Add validator list from indexer
> Staking list show complete validator list from indexer

- packages/e2e-tests/recover/seedPhrase.spec.js
- packages/frontend/src/components/common/GlobalAlert.js
- packages/frontend/src/components/common/modal/Modal.js
- packages/frontend/src/services/coreIndexer/CoreIndexerAdapter.ts
fix import new account not funded should be able import as implicit account with zero balance
add e2e test import account
> fix(account): allow import account zero balance

- packages/frontend/src/components/common/BackArrowButton.js
- packages/frontend/src/components/common/image/ImageWithLoading.tsx
- packages/frontend/src/components/common/loader/LoadingSkeleton.tsx
- packages/frontend/src/components/common/loader/LoadingSpinner.tsx
- packages/frontend/src/components/nft/NFTDetail.js
- packages/frontend/src/components/nft/NFTMedia.js
- packages/frontend/src/components/nft/NFTTransferModal.js
- packages/frontend/src/components/transactions/TransactionItem.tsx
- packages/frontend/src/components/transactions/TransactionItemModal.js
- packages/frontend/src/components/wallet/NFTBox.js
- packages/frontend/src/components/wallet/NFTs.js
- packages/frontend/src/components/wallet/Wallet.js
- packages/frontend/src/hooks/useImageLoading.ts
- packages/frontend/src/redux/slices/nft/index.js
- packages/frontend/src/redux/slices/transactionHistory/index.ts
- packages/frontend/src/routes/WalletWrapper.js
- packages/frontend/src/services/NonFungibleTokens.js
- packages/frontend/src/services/coreIndexer/CoreIndexerAdapter.ts
- packages/frontend/src/services/coreIndexer/indexers/AbstractCoreIndexer.ts
- packages/frontend/src/services/coreIndexer/indexers/FastNearIndexer.ts
- packages/frontend/src/services/coreIndexer/indexers/MintbaseIndexer.ts
- packages/frontend/src/services/coreIndexer/indexers/NearblocksV1Indexer.ts
- packages/frontend/src/services/coreIndexer/indexers/NearblocksV3Indexer.ts
- packages/frontend/src/services/coreIndexer/types/coreIndexer.type.ts
- packages/frontend/src/services/coreIndexer/types/mintbaseIndexer.type.ts
Nft Improvement
- Add NFT description and attributes
- Show better UI on nft list & nft detail
- Responsive UI on mobile
- Show loading bar for loading NFT image & NFT list
- Fetch NFT list from multiple indexer with race, to fix NFT list not showing if one of the indexer is down
Bugfix:
- Fix NFT transaction history metadata showing undefined on UI
- Go to NFT page detail, reload the page, press the back button, then NFT will be duplicated
> NFT page improvement

- packages/frontend/src/pages/TokenSwap/utils/constants.ts
swap show warning on high slippage for low liquidity swap.
reduce warning threshold
> fix(swap): update swap threshold

- packages/frontend/src/components/nft/NFTDetail.js
- packages/frontend/src/components/nft/NFTDetailWrapper.js
- packages/frontend/src/redux/slices/nft/index.js
- packages/frontend/src/redux/slices/transactionHistory/index.ts
- packages/frontend/src/translations/locales/en/translation.json
- packages/frontend/src/translations/locales/it/translation.json
- packages/frontend/src/translations/locales/pt/translation.json
- packages/frontend/src/translations/locales/ru/translation.json
- packages/frontend/src/translations/locales/ua/translation.json
- packages/frontend/src/translations/locales/vi/translation.json
- packages/frontend/src/translations/locales/zh-hans/translation.json
- packages/frontend/src/translations/locales/zh-hant/translation.json
- packages/frontend/src/utils/array.test.js
- packages/frontend/src/utils/array.ts
- Fix NFT detail attributes should show if visiting the page from homepage
- Fix NFT detail with different spec show attributes from extra
- Should hide button loadmore if less than the limit per page
- Add loading bar when fetch attributes
> Nft improvement

- packages/frontend/src/components/accounts/RecoverAccount.js
reorder import UI, make frequently used import account ex: seed phrase is the first order
> feat(account-import): reorder import account UI

- packages/frontend/src/app/App.js
- packages/frontend/src/components/connection/Connection.tsx
- packages/frontend/src/translations/locales/en/translation.json
- packages/frontend/src/utils/mnw-api-js/src/RpcRotator.ts
- packages/frontend/src/utils/storage/src/ConnectionsStorage.ts
UX improvement on rpc selector page
- Easier to change rpc with one click
- Add list of available free rpc
> RPC selector UX improvement

- packages/frontend/src/config/environmentDefaults/mainnet.ts
- packages/frontend/src/config/environmentDefaults/mainnet_STAGING.ts
- packages/frontend/src/utils/mnw-api-js/src/RpcRotator.ts
- packages/frontend/src/utils/mnw-api-js/test/rpc-provider.spec.ts
- packages/frontend/src/utils/storage/src/ConnectionsStorage.ts
use official near rpc as default
> fix(rpc): use official near rpc

- packages/frontend/src/redux/slices/transactionHistory/constant.ts
- packages/frontend/src/redux/slices/transactionHistory/transactionPattern.tsx
- near deposit amount
- fix swap wrong interpret
- near withdraw
- add_access_key
> feat(sign): interpret wrap

- packages/frontend/src/components/accounts/ledger/SelectAccountImport.tsx
- packages/frontend/src/redux/slices/transactionHistory/transactionPattern.tsx
> feat(sign): tx improve UI

- packages/frontend/src/redux/actions/staking.js
- packages/frontend/src/services/FungibleTokens.js
- packages/frontend/src/services/NonFungibleTokens.js
- packages/frontend/src/utils/wallet.ts
temporary revert transaction executor
> feat(tx-executor): revert tx executor

- packages/frontend/src/redux/slices/transactionHistory/transactionPattern.tsx
- packages/frontend/src/translations/locales/en/translation.json
interpret deplayed unstake metapool
> feat(tx): interpret deplayed unstake metapool

- packages/frontend/src/components/staking/components/Staking.js
- packages/frontend/src/components/staking/liquid-staking/StakingForm.tsx
- packages/frontend/src/components/staking/liquid-staking/UnstakeForm.tsx
handle max button liquid staking
> feat(staking): handle max button liquid staking

- packages/frontend/src/components/common/Tooltip.js
- packages/frontend/src/components/sign/v2/TransactionInterpretationItem.tsx
- packages/frontend/src/components/staking/components/ValidatorBoxItem.tsx
- packages/frontend/src/components/staking/liquid-staking/LiquidStakingContainer.tsx
- packages/frontend/src/components/staking/liquid-staking/StakingForm.tsx
- packages/frontend/src/components/staking/liquid-staking/SuccessAction.tsx
- packages/frontend/src/components/staking/liquid-staking/SuccessActionContainer.tsx
- packages/frontend/src/components/staking/liquid-staking/UnstakeForm.tsx
- packages/frontend/src/components/staking/liquid-staking/ValidatorDetail.tsx
- packages/frontend/src/components/transactions/TransactionItem.tsx
- packages/frontend/src/components/transactions/TransactionItemModal.js
- packages/frontend/src/redux/slices/transactionHistory/constant.ts
- packages/frontend/src/redux/slices/transactionHistory/transactionPattern.tsx
Handle Ledger liquid staking on error
Liquid Staking success modal
> fix ledger staking

- packages/frontend/src/components/staking/liquid-staking/UnstakeForm.tsx
Unstake page usemax button with large amount doesn't works
Fix input amount parser
https://github.com/user-attachments/assets/8e359f3a-6473-4976-8a71-36d8e612237f
> fix(staking): fix unstake amount parser

- packages/frontend/src/components/accounts/RecoverAccountPrivateKey.js
- packages/frontend/src/components/accounts/RecoverAccountSeedPhrase.js
- packages/frontend/src/components/accounts/ledger/SelectAccountImport.tsx
- packages/frontend/src/components/accounts/ledger/SignInLedgerWrapper.js
- packages/frontend/src/translations/locales/en/translation.json
- packages/frontend/src/utils/wallet.ts
If one account have multiple public key, they will always import the last one
Now user can select which account they want to import
Tested
- import account with seedphrase multikey
- import account with seedphrase single key
- import account with private key
- import account with ledger
> feat(account): import account can select specific accounts to import

- packages/frontend/src/services/coreIndexer/indexers/FastNearIndexer.ts
inactive validator sometimes not showing
fix inactive validator should show
> fix(staking): should show invalid validator list

- packages/frontend/package.json
- packages/frontend/src/translations/locales/en/translation.json
- packages/frontend/src/utils/mnw-api-js/src/RpcRotator.ts
- packages/frontend/src/utils/mnw-api-js/test/rpc-provider.spec.ts
- packages/frontend/src/utils/storage/src/ConnectionsStorage.ts
- packages/frontend/src/utils/storage/src/ObjectStorage.ts
rpc often unstable
add more rpc option, meteor fastnear as default
> Add rpc meteor fastnear

- packages/frontend/src/components/buy/FundingType.tsx
- packages/frontend/src/config/buyNearConfig.js
- packages/frontend/src/utils/moonpay.js
fix moonpay explore section was onclick do nothing
> fix(explore): moonpay url

- packages/frontend/src/utils/mnw-api-js/test/rpc-provider.spec.ts
> sync mainnet

- .github/workflows/stackhawk.yml
- packages/frontend/README.md
- packages/frontend/src/components/login/v2/ConfirmLogin.js
- packages/frontend/src/components/login/v2/ConfirmLoginWrapper.js
- packages/frontend/src/redux/actions/account.js
- packages/frontend/src/redux/slices/activeAccount/index.js
Users reported being unable to log in to dApps
- Add an error message for users.
- Make Mixpanel async to avoid blocking requests on error.
> fix login dapps stuck
