mynearwallet/my-near-wallet

packages/frontend/src/services/NonFungibleTokens.js

fix: remove outer FunctionCallError in NFT metadata error matching

---

packages/frontend/package.json
packages/frontend/src/components/accounts/batch_import_accounts/index.js
packages/frontend/src/utils/encoding.js
yarn.lock

Update the decryption implementation to use wallet-selector/account-export package

feat: replacing the decryption with wallet-selector/account-export

---

packages/frontend/package.json
packages/frontend/src/components/accounts/CreateAccount.js
packages/frontend/src/components/accounts/LinkdropLanding.js
packages/frontend/src/components/accounts/SetupSeedPhrase.js
packages/frontend/src/components/accounts/linkdrops/NearDropLanding.js
packages/frontend/src/components/accounts/linkdrops/TrialDropLanding.js
packages/frontend/src/redux/actions/account.js
packages/frontend/src/redux/slices/account/createAccountThunks.js
packages/frontend/src/translations/locales/en/translation.json
packages/frontend/src/utils/wallet.js

- Layed the foundational work for different linkdrop types and rendering the linkdrop landing page accordingly.
- Introduced Trial Account Offboarding flow as a new type of linkdrop (more info found [here](https://docs.keypom.xyz/docs/next/TrialAccounts/offboarding))
- New linkdrop standard calls for different interfaces and methods. This has been (mostly) addressed in this PR
- Small bugfixes
Trial Account flow is as follows:
1. The linkdrop landing page now looks as follows (this is *only* for trial accounts):
2. When the button is clicked, they go through the regular linkdrop claiming flow (except they don't choose an account ID):
- Choose recovery method
- Verify recovery method
- Create Account
A full demo:
https://drive.google.com/file/d/1hD1oFvO_RG5-PvzWJUvj-B96rniWY2zO/view?usp=sha …

feat: To reverted master: Add new linkdrop standard fixes & trial account offboarding

---

packages/e2e-tests/fungibleToken/fungibleToken.spec.js
packages/frontend/src/components/common/FormButton.js
packages/frontend/src/components/common/balance/FiatBalance.tsx
packages/frontend/src/components/send/components/views/EnterAmount.js
packages/frontend/src/redux/slices/swap/index.js
packages/frontend/src/redux/slices/tokens/index.js
packages/frontend/src/translations/locales/en/translation.json
packages/frontend/src/translations/locales/it/translation.json
packages/frontend/src/translations/locales/pt/translation.json
packages/frontend/src/translations/locales/ru/translation.json
packages/frontend/src/translations/locales/tr/translation.json
packages/frontend/src/translations/locales/ua/translation.json
packages/frontend/src/translations/locales/vi/translation.json
packages/frontend/src/translations/locales/zh-hans/translation.json
packages/frontend/src/translations/locales/zh-hant/translation.json
packages/frontend/src/utils/token.test.js
packages/frontend/src/utils/token.ts
packages/frontend/src/wallet.d.ts

Change some of the token's symbol to more human readable.
eg: Bridged USDT, Native USDT
The work is largely based on https://github.com/mynearwallet/my-near-wallet/pull/126

change token namings

---

packages/frontend/src/utils/wallet.js

Main-T-224 MNW is creating FullAccessKey every time it recovers from seed phrase or private key
Stopping it from creating the FullAccessKey
This changes is not meant to be long term, it is meant to be a hot fix. After PR #145 resolves, definitely the whole `recoverAccountSecretKey` and related functions need to be rewritten, they are too messy.

fix: stop creating FullAccessKey when recovering account

---

packages/frontend/src/config/configFromEnvironment.ts
packages/frontend/src/config/environmentDefaults/development.ts
packages/frontend/src/config/environmentDefaults/mainnet.ts
packages/frontend/src/config/environmentDefaults/mainnet_STAGING.ts
packages/frontend/src/config/environmentDefaults/testnet.ts
packages/frontend/src/config/environmentDefaults/testnet_STAGING.ts
packages/frontend/src/services/PrivateShard.js

1. The Calimero authentication token (x-api-token) was not included in the API headers.
2. The body was missing the call method.
1. The sync function now directly calls the Calimero gateway API instead of the Calimero console API.
2. The "method" field has been added to the body.
3. The "x-api-key" has been added to the call headers.
The purpose of these changes is to verify that the passed x-api-key has the appropriate permissions for "sync" and that the permission matches the value of the method passed in the body.

[calimero] change sync endpoint and call payload

---

packages/frontend/src/pages/TokenSwap/ui/Preview.js
packages/frontend/src/pages/TokenSwap/ui/SwapForm.js

When swapping, will show price impact warning when more than threshold.
When the price impact is too unreasonable, will show error and disable button instead

feat: show warning/error when price impact more than threshold

---

packages/frontend/src/components/send/SendContainerV2.js

Updated the explorer URI from the legacy explorer /transactions to the NEARBlocks.io txn
Update /transactions to /txns to match NEARBlocks expected URI format
1. Send 1N to another address
2. Click "View in Explorer" 
3. FIX: Link now takes the user to the actual transaction in NEARBlocks instead of a 404 page

Update transaction -> txns to support NEARBlocks URI Format

---

packages/frontend/src/components/sign-message/SignMessage.js

This PR improves the CSS style on the `sign-message` route for the long accountId (e.g. implicit accountIds) name.
Fixes text overflow.

Improve style for accountId in sign-message route

---

packages/frontend/src/components/common/token/TokenBox.js
packages/frontend/src/redux/slices/security/temp_blacklisted_tokens.json

It appears that blacklisting a tokens is not a new feature. it is something already done previously.
So I removed the newly added code, and move the blacklisted tokens to the place where it originally is designed.

refactor: move blacklisted tokens feature to originally designed place

---

packages/frontend/src/redux/actions/staking.js

Some staking pool reward user with fungible tokens, such as `aurora.pool.near`
This patch fixes the bug where user can't claim staking rewards from this kind of pool

fix: User can't claim FT from staking pool

---

packages/frontend/src/components/accounts/RecoverAccountSeedPhrase.js
packages/frontend/src/config/environmentDefaults/development.ts
packages/frontend/src/config/environmentDefaults/mainnet.ts
packages/frontend/src/config/environmentDefaults/mainnet_STAGING.ts
packages/frontend/src/config/environmentDefaults/testnet.ts
packages/frontend/src/config/environmentDefaults/testnet_STAGING.ts
packages/frontend/src/services/indexer/api.js

This happens when the user created an account, then import it using seed phrase within a very short period.
Kitwallet API is slow when registering changes.
I have added NearBlocks API.
The original Kitwallet API is not removed, instead, now the wallet will call both the Indexer, and merge their results together.
By doing so, we remove the single point of failure...
Now, no matter kitwallet is failing or nearblocks is failing, our wallet won't be affected. Our wallet will only be affected if both the indexer fails.

fix: user can't import account with seed phrase

---

packages/frontend/src/redux/slices/tokens/index.js

All FT tokens will be filter out if:
- Their length is more than 10 characters, including 10
- They contain any character except these: "a-z", "A-Z", "0~9"

fix: filter weird symbol FT tokens

---

packages/frontend/src/redux/actions/account.js
packages/frontend/src/utils/wallet.ts

The changes introduced in PR #179 are being modified due to the following concerns:
 1.⁠ ⁠*Signer Passing to External Library:* In line 271, the PR passes our signer to an external library, which raises concerns about the security of our application.
 2.⁠ ⁠*External Library Inspection:* We have thoroughly reviewed the external library, "calimero-wallet-utils," up to version 0.0.1 and found no issues. However, it's important to note that the library's version is specified with a caret "^," indicating that future updates to the external library could potentially introduce security risks as our signer is being passed to it.
We are modifying these changes to ensure the security and stability of our application.
1. "signer" is no longer being passed into the external library.
2. Since "signer" …

refactor: not passing signer into external library

---

packages/frontend/src/redux/slices/tokens/index.js

Tokens such as USDC.e is not showing after PR-181 patch because it contains invalid symbol such as "decimal"
After some consideration, we don't want to "allow" any symbol.
Instead of allowing symbol, we will whitelist "USDC.e" and "USDT.e"

fix: whitelist USDC.e and USDT.e

---

packages/frontend/src/redux/slices/tokens/index.js

Fixing an issue where Bridged USDT and Bridged USDC are not showing. This issue happened earlier due to a previous commit that's trying gatekeep users from phishing tokens. Both "Bridged USDT/USDC" have longer than 10 characters symbols and were both blocked. 
Added a condition check to just let both tokens go through

fix: showing USDT.e and USDC.e

---

packages/frontend/src/hooks/getCurrentLanguage.js

When the currentLanguage is undefined, reading "code" will cause the code to throw error.
This PR edit the code to give a default value when currentLanguage?.code is undefined.

fix: set a default language code when current language is not available

---

packages/frontend/src/translations/locales/pt/translation.json

Portuguese translations fixed. There were sections in English and Italian.
The **setupPasswordProtection, setupSeedPhrase ** sections have been fixed because they were in Italian and English
file located at:  my-near-wallet\packages\frontend\src\translations\locales\pt\translation.json

fix: updated Portuguese translations

---

packages/frontend/src/utils/signMessage.ts

Original issue: 
Currently the `nonce` is being passed as a string of [ASCII characters](https://www.asciitable.com/) characters  from `wallet-selector` in case the `nonce` Buffer contains any value greater than `128` it adds these symbols to the URL which results in strange behavior such as errors either like: 
_Array length 60 does not match schema length 32 at value.nonce_
OR
This PR adds the possibility to handle the case when the nonce is passed to the URL as a `base64` string which is more URL-safe but still keeps the old functionality to avoid breaking changes for the current and older versions of the `wallet-selector`
Changes made to wallet-selector to fix the issue: https://github.com/near/wallet-selector/pull/1067

Handle the case when nonce is a base64 string for signMessage

---

packages/frontend/src/services/indexer/api.ts
packages/frontend/src/utils/request.js

Adding a new method, fetchWithTimeout, to improve fetching account IDs from indexers. This resolves issues caused by slow indexers, ensuring the feature works more reliably.

fix: adding timeout to import account indexer apis

---

.eslintrc.js
packages/frontend/src/redux/actions/staking.js
packages/frontend/src/utils/staking.ts

Staking page breaks currently due to kitwallet api went down.
Replacing current getStakingDeposits method with RPC get_total_staked_balance method. Also get list of validators from rpc using rpc.validators() method

fix: replacing kitwallet api with rpc in getStakingDeposits metho

---

packages/frontend/src/services/indexer/api.ts
packages/frontend/src/utils/request.js

At the current time of testing:
Mintbase API will inconsistently success after 40+ seconds or failed after 1 minutes.
---
Kitwallet API will consistently failed after 1 minutes
---
Nearblocks API will consistently success after 10~30 seconds
---
I think a 30 seconds timeout is more reliable.

fix: set timeout to become 30 seconds

---

packages/frontend/src/config/environmentDefaults/development.ts
packages/frontend/src/config/environmentDefaults/mainnet.ts
packages/frontend/src/config/environmentDefaults/mainnet_STAGING.ts
packages/frontend/src/config/environmentDefaults/testnet.ts
packages/frontend/src/config/environmentDefaults/testnet_STAGING.ts
packages/frontend/src/services/indexer/api.ts

User is reporting that they can't find all their account when trying to import with ledger.
After our debugging, we found out that maybe Nearblocks v1 api doesn't capture every account properly.
We added fastnear API to support the account import, while also remove nearblocks v1.
+ Add fastnear API for checking account with public key when importing account
- Remove nearblocks v1 for checking account with public key when importing account

feat: use fastnear API to import account

---

packages/frontend/src/utils/account-with-lockup.ts
packages/frontend/src/utils/staking.ts

Users are reporting about the issue that they can't see their Near balance.
---
After some investigation, we found out that the issue is caused by PR #205, which now try to find staking providers from RPC.
However, not all validators actually support staking. Some of them not even have contract deployed.
---
After the fix, now the near balance will show properly
---
Staking page will works properly too

fix: not all validators support staking

---

packages/frontend/src/config/environmentDefaults/mainnet.ts

The API provided by Nearblocks has been switched to a new subdomain, https://api.nearblocks.io/. However, the wallet is still using https://api3.nearblocks.io/, causing an error when fetching the list of tokens and NFTs for users.
Nearblocks API Documents: https://api.nearblocks.io/api-docs/
Update https://api3.nearblocks.io to https://api/.nearblocks.io in mainnet environment configs.

fix: domain api nearblocks for likely tokens and likely nfts

---

packages/frontend/src/redux/slices/account/createAccountThunks.js
packages/frontend/src/utils/wallet.ts

Recently we changed kitwallet API to become nearblocks API, however, some of the API won't work under the new API.
We need to change the account creation API back to kitwallet provider

fix: zero balance account creation failure

---

packages/frontend/src/components/staking/StakingContainer.js
packages/frontend/src/components/staking/components/StakingAction.js

Staking always show success page and on ledger it show success first before approve on ledger
allow staking & unstake waiting for result before showing success page
stake
unstake
stake with ledger
unstake with ledger

fix(staking): was always success and not wait for loading

---

packages/frontend/src/config/environmentDefaults/mainnet_STAGING.ts
packages/frontend/src/services/indexer/api.ts
packages/frontend/src/utils/moonpay.js
packages/frontend/src/utils/twoFactor.js
packages/frontend/src/utils/wallet.ts

Thanks to user `elorpar.near` and an anonymous user who contributed a lot of info in debugging on this issue.
Currently, users who get their account from initial coin offering, can't sign any transaction.
----
After some investigation, we believe that PR #211 broke the mechanism.
----
Thus, we make the necessary changes back.
----
We did create an account and able to replicate the error that user told us, which is "Not found".
However, since the account that i use is created by myself, thus I can't further test it.... I have tried to deployed a multisig contract into my account, but sadly my account is not the real "ICO account"
My fake multisign account will show this error, because it is not the multisig account that near team give to users.
----
Thus, we are now proceed to trying to …

Near ICO multisig users fix.

---

packages/frontend/src/components/accounts/RecoverAccountPrivateKey.js
packages/frontend/src/components/accounts/RecoverAccountSeedPhrase.js
packages/frontend/src/components/common/GlobalAlert.js
packages/frontend/src/services/indexer/api.ts
packages/frontend/src/translations/locales/en/translation.json
packages/frontend/src/utils/wallet.ts

Deleted private access key account was able imported into wallet, & user cant do any transaction
Most error reported:
Can not sign transactions for account .... on network default, no matching key pair found
It will resolve this issue for new user who import invalid seedphrase with incorrect private key to the wallet, but for existing user will have same behavior no changes & they need to import with valid seedphrase with correct full access key
when import deleted all full access key  / deleted private key will show error
1. import account with deleted full access key, and found on indexer, should show error no matching keypair
2. import account with deleted full access key, and deleted on indexer will imported as implicit account with zero balance, because we cant find the account on …

import account access key checker

---

packages/frontend/src/config/environmentDefaults/development.ts
packages/frontend/src/config/environmentDefaults/testnet.ts
packages/frontend/src/config/environmentDefaults/testnet_STAGING.ts
packages/frontend/src/redux/slices/tokens/topTokens.json
packages/frontend/src/services/indexer/api.ts

some token not show on list ex: usdc native, 
when hit indexer with wrong param fromBlockTimestamp from cache, server will not response
now fromBlockTimestamp param no longer needed

fix(token): fix show all token

---

packages/frontend/src/components/accounts/password_encryption/UnlockWalletPage.tsx

I can't snipe fast enough :(
Made the WalletUnlock page trigger the unlock when the Enter key is pressed, behaving more like a usual form.
I've made sure to only add this to the WalletUnlock page so people don' trigger sending a transaction by mistake but can still unlock their wallets just a wee bit faster :)
When me and my Degen friends play on NEAR we like to stay as native as possible in wallet solutions  💖
Please do let me know if I should've done this any other way since it's the first time I've seen React.

🚸(ux):  press 'Enter' to submit the password

---

packages/frontend/src/components/login/v2/ConfirmLoginWrapper.js

login dapps with ledger sometimes doesnt works & it trigger not by button
on login dapps page, the function triggers on page visit, it is not intended, should be triggered by a button click.
this is why previously users should revisit the page multiple times and sometimes it can login to dapps
solution:
wrap the trigger in a function so it only triggered by a button click
tested
-login with ledger
-login without ledger

fix(dapps): login ledger

---

packages/frontend/src/components/common/token/TokenBox.js
packages/frontend/src/utils/fiatValueManager.js

Some token prices with a lot of decimals not showing example Blackdragon
Show token prices and the fiat value owned by user
Before:
After:

fix(tokens): should show tokens fiat value with many decimals

---

packages/frontend/src/config/environmentDefaults/mainnet.ts
packages/frontend/src/config/environmentDefaults/mainnet_STAGING.ts
packages/frontend/src/utils/wallet.ts

The PR222 introduces a check to ensure that full access keys are present while importing an account. However, not all valid imports necessarily include full access keys in their account configuration.
Certain multisig accounts, like multisig.pierre-dev.near, do not possess full access keys but are still valid for import. These accounts rely on limited access keys for their functionality and should be allowed to be imported.
Screenshot below shows that before the fix, account `multisig.pierre-dev.near` can't be imported.
Screenshot below shows that after the fix, account `multisig.pierre-dev.near` can be imported successfully.

fix: pr222 broken multisig account login

---

packages/frontend/src/utils/accountsLogic/withAdjustedStorageCost.ts
packages/frontend/src/utils/wallet.ts

Account with large amount of storage staked (as example, those account with contract deployed, such as multisig), when trying to send near, and press "max", they will end up have insufficient amount of near to support storage cost.
This ends up wasting user's gas fee and they will fail repeatedly again and again unless they choose to send a smaller amount of near manually.
I hijacked the `getAccountBalance` from `near-api-js` `Account`, increasing the storage staking cost by 2.4%.
The reason of why the increment is 2.4% is because from the response of RPC providers, it seems like the shortage is around 2.1%
I am making a smart guess that maybe the calculation of "binary thousands" and "digital thousands", i.e. 1000 vs 1024 is causing the problem. We are expressing thousands as 1000 in …

fix: storage cost calculation

---

packages/frontend/src/components/profile/full_access_key_rotations/FullAccessKeyRotation.js
packages/frontend/src/translations/locales/en/translation.json

The "Rotate Key" might be not user friendly.
We change it to "Use this key" so user can understand it better.

refactor: rename "rotate key" to become "use this key"

---

packages/frontend/src/components/wallet/Wallet.js
packages/frontend/src/redux/slices/tokens/index.js
packages/frontend/src/routes/WalletWrapper.js

Load near price loaded slower than the rpc call, for example near price need 5s to loaded on UI while rpc only take around 1s
findings: function loadAccount initial state when load token is return empty balance
Get account balance on initial account state
the result loading near token balance is faster
Tested:
- implicit account zero balance
- regular named account with ft tokens

fix(tokens): near token balance should load faster

---

packages/frontend/src/redux/slices/transactionHistory/transactionPattern.tsx

Improve transaction history UI for ft_transfer_call should show as transfer transaction

feat(transaction-history): ft transfer UI

---

packages/frontend/src/components/accounts/ledger/SelectAccountImport.tsx
packages/frontend/src/components/accounts/ledger/SignInLedgerViews/ImportAccounts.js
packages/frontend/src/components/accounts/ledger/SignInLedgerWrapper.js
packages/frontend/src/redux/slices/ledger/index.js
packages/frontend/src/translations/locales/en/translation.json
packages/frontend/src/translations/locales/it/translation.json
packages/frontend/src/translations/locales/pt/translation.json
packages/frontend/src/translations/locales/ru/translation.json
packages/frontend/src/translations/locales/vi/translation.json
packages/frontend/src/translations/locales/zh-hans/translation.json
packages/frontend/src/translations/locales/zh-hant/translation.json

Import account with ledger can select multiple account to import rather than import all account

feat(ledger): import account ledger selectable

---

packages/frontend/src/redux/actions/staking.js

Issue:
when change to other rpc example fastnear or lava, the staking balance will show 0
Fixed:
all rpc show staking balance

fix(staking): all rpc show staking balance

---

packages/frontend/src/components/common/image/ImageWithLoading.tsx
packages/frontend/src/components/sign/v2/SignTransaction.js
packages/frontend/src/components/sign/v2/SignTransactionSummary.js
packages/frontend/src/components/sign/v2/TransactionInterpretationItem.tsx
packages/frontend/src/redux/slices/transactionHistory/index.ts
packages/frontend/src/redux/slices/transactionHistory/transactionPattern.tsx
packages/frontend/src/redux/slices/transactionHistory/type.ts

When signing from dapps, should show transaction interpretation. Users should understand what they signing, for example, sending fund before they approve the transaction
- Ref finance swap
- Ref finance add liquidity
- Ref finance stake liquidity pool
- Burrow supply
- Burrow staking
- Burrow withdraw
- Paras buy nft
- Linear staking
- Linear liquid unstake

feat(tx-interpret): sign transaction interpretation

---

packages/frontend/src/components/staking/components/ValidatorBoxItem.tsx
packages/frontend/src/components/staking/liquid-staking/StakingForm.tsx
packages/frontend/src/components/staking/liquid-staking/UnstakeForm.tsx
packages/frontend/src/components/transactions/ExecutorModal/TransactionExecutorModal.tsx
packages/frontend/src/redux/slices/transactionHistory/transactionPattern.tsx

- Liquid stake, unstake form button usemax
- Transaction history liquid unstake

fix(stake): ux, liquid unstake interpret

---

packages/frontend/src/components/staking/components/FarmingAPY.js
packages/frontend/src/components/staking/components/ValidatorBox.js
packages/frontend/src/translations/locales/en/translation.json

Validator that have no farm was show as 0 APY, should show as Farm APY

fix(staking): fix apy when validator not have farm data

---

packages/frontend/src/services/NonFungibleTokens.js
packages/frontend/src/utils/mnw-api-js/test/rpc-provider.spec.ts

nft url have double slash causing image not loaded
example url
https://bafybeicoyahgprpxedl5iszszm474xy6verklojpafd7tmp5tibh3yoc3i.ipfs.dweb.link//1264.png
solution: remove slash at the end of nft base uri

fix nft url

---

packages/frontend/src/config/environmentDefaults/development.ts
packages/frontend/src/config/environmentDefaults/mainnet.ts
packages/frontend/src/config/environmentDefaults/mainnet_STAGING.ts
packages/frontend/src/config/environmentDefaults/testnet.ts
packages/frontend/src/config/environmentDefaults/testnet_STAGING.ts

Account helper URLs have moved to
- https://helper.mainnet.near.org/
- https://helper.testnet.near.org/

fix: update account helper url

---

packages/frontend/src/services/NonFungibleTokens.js

The Cloudflare IPFS gateway https://cloudflare-ipfs.com has been turned down, which causes some NFTs in MyNearWallet cannot be displayed correctly. 
Let's switch to https://ipfs.io or https://dweb.link.
Links:
- https://www.reddit.com/r/ipfs/comments/1cuw1r4/cloudflares_ipfs_gateway_will_be_turned_down_in
- https://blog.cloudflare.com/cloudflares-public-ipfs-gateways-and-supporting-interplanetary-shipyard
Replace https://cloudflare-ipfs.com with https://ipfs.io

fix: replace cloudflare ipfs gateway

---

packages/frontend/src/routes/SignMessageWrapper.js
packages/guestbook/src/components/Content.tsx

MyNearWallet currently always includes the callbackUrl in signMessage, this makes MNW behave different than other wallets.
With the new release of wallet-selector, MNW will now open in a pop-up window, for which users will also expect it to work in the same way as other wallets, i.e. to not include the callbackUrl in the signMessage
This PR changes MNW, so it includes the callbackURL when called as a BrowserWallet (i.e. it redirects the user), and excludes it when using MNW as a Injected Wallet (i.e. in a pop-up)

feat: wallet-selector no longer include callback to sign

---

packages/frontend/src/components/common/Footer.js
packages/frontend/src/components/common/GlobalAlert.js

This discord invite is expired [https://discord.com/invite/Vj74PpQYsh](https://discord.com/invite/Vj74PpQYsh)
I found the right link in the [x bio](https://x.com/MyNearWallet) [https://discord.gg/XUPPddjVcr](https://discord.gg/XUPPddjVcr)
1. The discord link in the header and footer of https://www.mynearwallet.com/. 
2. The question? Join community link in the footer of https://app.mynearwallet.com/ 
3. The linktree invite to the discord server is also expired
Also the FAQ popup when a transactions failed still points to zendesk instead of the newer help center supported by gleap: https://help.mynearwallet.com/en 
I replaced the discord link with the version that works
The footer:

Fix: Update discord link

---

packages/e2e-tests/utils/connectionSingleton.js
packages/frontend/src/config/environmentDefaults/development.ts
packages/frontend/src/config/environmentDefaults/mainnet.ts
packages/frontend/src/config/environmentDefaults/mainnet_STAGING.ts
packages/frontend/src/config/environmentDefaults/testnet.ts
packages/frontend/src/config/environmentDefaults/testnet_STAGING.ts

DNS issue on helper.mainnet.near.org, causing some features doesn't works as intended, example create account
Update with temporary URL https://neardev-mainnet-account-helper.onrender.com

fix: update near helper url

---

packages/frontend/src/components/login/v2/SelectAccountLoginWrapper.js

This update expands on [PR #288](https://github.com/mynearwallet/my-near-wallet/pull/288) with further improvements
Changes Description
- Wallet selector functionality remains unchanged in versions below v9
- Fix the issue when the user clicks "Cancel Login" while using wallet-selector v9, the expected behavior is for the popup to close. However, the current implementation redirects the user instead.

feat: send message when user cancel the login

---

packages/frontend/src/redux/slices/signMessage/index.js
packages/frontend/src/utils/wallet.ts

Background: 
Sign message does not require any deposit. Non-funded accounts should be able to sign messages
Changes Description:
- Funded account (Ledger / non-Ledger): Works using the same previous code 
- Non-funded implicit account: Works using the near-api-js verify function.
- Non-funded implicit account with Ledger: Will throw an error

fix: allow nonfunded account signmessage

---

packages/frontend/src/redux/slices/account/createAccountThunks.js
packages/frontend/src/services/coreIndexer/indexers/MintbaseIndexer.ts
packages/frontend/src/utils/wallet.ts

- Fixed Import Wallet Timeout Issue: 
Importing wallets often timed out on the indexer https://interop-testnet.hasura.app/v1/graphql, causing users to wait more than 60 seconds to see results. This issue was resolved by removing it, as other indexers already handle it, and make the fetching return the first successfull one
- Resolved Create Wallet Error: 
Fixed an error encountered during wallet creation: `UnrecognizedClientException: The security token included in the request is invalid` on the https://helper.mainnet.near.org/ API by trycatch non critical api hit

hotfix api error on create & import wallet

---

packages/frontend/src/components/login/v2/SelectAccountLoginWrapper.js
packages/frontend/src/redux/actions/account.js
packages/frontend/src/routes/SignMessageWrapper.js
packages/frontend/src/routes/SignWrapper.js

Background: Some users experience issues when signing transactions on dApps. The button keeps showing a loading state without redirecting, even though the transaction has already gone through
Findings: This issue occurs only with dApps using Wallet Selector < 9 and when users have installed certain browser extensions that interfere with the window opener
Fixes: Add a fallback redirect in case the issue is caused by an unintended interference with window.opener, such as by a browser extension

fix: add fallback redirect for window opener conflict after sign dapps

---

packages/e2e-tests/utils/connectionSingleton.js
packages/frontend/src/config/environmentDefaults/development.ts
packages/frontend/src/config/environmentDefaults/mainnet.ts
packages/frontend/src/config/environmentDefaults/mainnet_STAGING.ts
packages/frontend/src/config/environmentDefaults/testnet.ts
packages/frontend/src/config/environmentDefaults/testnet_STAGING.ts

Reverts mynearwallet/my-near-wallet#297 because https://helper.mainnet.near.org/ is operational again, making the temporary URL https://neardev-mainnet-account-helper.onrender.com/ unnecessary

Revert "fix: update near helper url"

---

packages/frontend/src/utils/mnw-api-js/src/RpcRotator.ts
packages/frontend/src/utils/storage/src/ConnectionsStorage.ts
packages/frontend/src/utils/storage/src/ObjectStorage.ts

Added custom RPC is not saved when the page is reloaded.
- Fixed: Custom-added RPC now retains its state after a page reload
- Added: Fastnear RPC for testnet
- Updated: Ankr RPC on mainnet now requires an API key
- Remove: Infura RPC for the testnet no longer exists
- Add custom RPC
- Switch primary RPC
- Legacy users with old RPC connections should have the newly added RPC connections included
- Should return the default RPC list for new users (incognito browser).

fix: custom added rpc should update on reload, add fastnear testnet

---

packages/frontend/src/config/environmentDefaults/mainnet.ts
packages/frontend/src/config/environmentDefaults/mainnet_STAGING.ts

Fixed an issue where the USD price of some new tokens, such as RHEA, was not displaying due to an outdated API

fix: some token not showing usd price
